---
#
# Playbook invoked by Kloigos after each `allocate` call.
#
# The following extra-vars are passed:
#   compute_id
#   hostname
#   ansible_host
#   server_private_ip
#   server_public_ip
#   private_ip
#   public_ip
#   system_user
#   cpu_range
#   cpu_count
#   ssh_public_key
#
#
- name: GATHER COMPUTE UNIT TO ALLOCATE
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
    - name: Build ansible inventory dynamically
      add_host:
        name: "{{ compute_id }}"
        ansible_user: ubuntu
        public_hostname: "{{ hostname }}"
        ansible_host: "{{ ansible_host }}"
        server_private_ip: "{{ server_private_ip }}"
        server_public_ip: "{{ server_public_ip | default('', true) }}"
        private_ip: "{{ private_ip }}"
        public_ip: "{{ public_ip | default('', true) }}"
        system_user: "{{ system_user }}"
        cpu_count: "{{ cpu_count }}"
        groups: new_alloc


- name: ALLOCATE COMPUTE UNIT
  hosts: new_alloc
  gather_facts: no
  become: yes
  tasks:
    - name: setup SSH key so user can login
      copy:
        content: |
          {{ ssh_public_key }}
        dest: /home/{{ system_user }}/.ssh/authorized_keys
        owner: "{{ system_user }}"
        group: "{{ system_user }}"
        mode: "0600"

    - name: create welcome file
      copy:
        content: |
          WELCOME TO COMPUTE UNIT `{{ compute_id }}`!

          This compute unit features:
            - CPU count: {{ cpu_count }}
            - Memory:
            - Max running processes: 
            - Private IP: {{ private_ip }}
            - Public IP: {{ public_ip | default('', true) }}
            - Network bandwidth:
            - Disk volume at /mnt/{{ system_user }}
            - IOPS/MBPS:

          
          You're not root, but you can still use systemd
          to run your services.
          Bind services explicitly to {{ private_ip }}.
          Make sure you save your .service files at directory

          ~/.config/systemd/user/

          and you manage the service using the `--user` flag, Example:  

          systemctl --user daemon-reload
          systemctl --user enable myservice
          systemctl --user start myservice

        dest: /home/{{ system_user }}/WELCOME.txt
