---
#
# Playbook invoked by Kloigos after each `deallocate` call.
#
#   compute_id
#   hostname
#   ansible_host
#   server_private_ip
#   server_public_ip
#   system_user
#
- name: GATHER COMPUTE UNITS TO DEALLOCATE
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
    - name: Build ansible inventory dynamically
      add_host:
        name: "{{ compute_id }}"
        ansible_user: ubuntu
        public_hostname: "{{ hostname }}"
        ansible_host: "{{ ansible_host }}"
        server_private_ip: "{{ server_private_ip }}"
        server_public_ip: "{{ server_public_ip | default('', true) }}"
        system_user: "{{ system_user }}"

        groups: dealloc

- name: CLEANUP COMPUTE UNIT
  hosts: dealloc
  gather_facts: no
  become: yes
  tasks:
    - name: finding id for user
      shell: |
        id -u {{ system_user }}
      register: user_id

    - name: remove ssh key to block any new connection
      shell: |
        rm -f /home/{{ system_user }}/.ssh/authorized_keys

    - name: stop the user systemd instance to stop any running process
      shell: |
        systemctl stop user@{{ user_id.stdout }}.service

    - name: severe any open connection
      shell: |
        loginctl kill-user {{ system_user }} || true

    - name: remove all files from the compute_unit
      shell: |
        rm -rf /home/{{ system_user }}/*
        rm -rf /opt/{{ system_user }}/*
        rm -rf /mnt/{{ system_user }}/*

    - name: recreate .ssh with safe perms (empty, no keys)
      shell: |
        mkdir -p /home/{{ system_user }}/.ssh
        chown {{ system_user }}:{{ system_user }} /home/{{ system_user }}/.ssh
        chmod 700 /home/{{ system_user }}/.ssh

        touch /home/{{ system_user }}/.ssh/authorized_keys
        chown {{ system_user }}:{{ system_user }} /home/{{ system_user }}/.ssh/authorized_keys
        chmod 600 /home/{{ system_user }}/.ssh/authorized_keys
