import datetime as dt
from enum import StrEnum, auto
from typing import Any

from pydantic import BaseModel, Field, model_validator


class AutoNameStrEnum(StrEnum):
    def _generate_next_value_(name, start, count, last_values):
        return name


class NoFreeComputeUnitError(Exception):
    pass


class NoFreeIpAddressError(Exception):
    pass


class ComputeUnitNotFoundError(Exception):
    pass


class ComputeUnitStateError(Exception):
    pass


class ComputeUnitOperationError(Exception):
    pass


class ServerNotFoundError(Exception):
    pass


class ServerStateError(Exception):
    pass


class MissingLicenseError(Exception):
    pass


class InvalidTokenError(Exception):
    pass


class UnknownSigningKeyError(Exception):
    pass


class InvalidSignatureError(Exception):
    pass


class ExpiredLicenseError(Exception):
    pass


class FeatureNotLicensedError(Exception):
    pass


def _cpu_ids_for_range(cpu_range: str) -> set[int]:
    raw_range = cpu_range.strip()
    if not raw_range:
        raise ValueError("cpu_range is empty.")

    step = 1
    if ":" in raw_range:
        raw_range, raw_step = raw_range.split(":", 1)
        step = int(raw_step)
        if step <= 0:
            raise ValueError("cpu_range step must be positive.")

    if "-" in raw_range:
        raw_start, raw_end = raw_range.split("-", 1)
        start = int(raw_start)
        end = int(raw_end)
    else:
        start = end = int(raw_range)

    if start < 0 or end < start:
        raise ValueError("cpu_range must be a non-negative start-end range.")

    return set(range(start, end + 1, step))


class Event(AutoNameStrEnum):
    SERVER_INIT_REQUEST = auto()
    SERVER_INIT_DONE = auto()
    SERVER_INIT_FAILED = auto()
    SERVER_DECOMM_REQUEST = auto()
    SERVER_DECOMM_DONE = auto()
    SERVER_DECOMM_FAILED = auto()
    SERVER_DELETE_REQUEST = auto()
    SERVER_DELETE_DONE = auto()
    SERVER_DELETE_FAILED = auto()
    CU_ALLOCATION_REQUEST = auto()
    CU_ALLOCATION_DONE = auto()
    CU_ALLOCATION_FAILED = auto()
    CU_DEALLOCATION_REQUEST = auto()
    CU_DEALLOCATION_DONE = auto()
    CU_DEALLOCATION_FAILED = auto()
    ALLOCATION_CREATE_REQUEST = auto()
    ALLOCATION_CREATE_DONE = auto()
    ALLOCATION_CREATE_FAILED = auto()
    ALLOCATION_SCALE_REQUEST = auto()
    ALLOCATION_SCALE_DONE = auto()
    ALLOCATION_SCALE_FAILED = auto()
    IP_POOL_INSERT = auto()
    IP_POOL_ALLOCATE = auto()
    IP_POOL_RELEASE = auto()
    IP_POOL_DELETE = auto()


class Playbook(AutoNameStrEnum):
    # compute unit level statuses
    CU_ALLOCATE = auto()
    CU_DEALLOCATE = auto()
    ALLOCATION_SCALE = auto()
    SERVER_INIT = auto()
    SERVER_DECOMM = auto()


class QueueCommand(AutoNameStrEnum):
    CU_ALLOCATE = auto()
    CU_DEALLOCATE = auto()
    ALLOCATION_SCALE = auto()
    SERVER_INIT = auto()
    SERVER_DECOMM = auto()


class ComputeUnitStatus(AutoNameStrEnum):
    # compute unit level statuses
    FREE = auto()
    ALLOCATING = auto()
    ALLOCATED = auto()
    ALLOCATION_FAIL = auto()
    DEALLOCATING = auto()
    DEALLOCATION_FAIL = auto()
    UNAVAILABLE = auto()


class AllocationStatus(AutoNameStrEnum):
    REQUESTED = auto()
    ALLOCATING = auto()
    ALLOCATED = auto()
    SCALING = auto()
    SCALE_FAIL = auto()
    DEALLOCATING = auto()
    DEALLOCATED = auto()
    ALLOCATION_FAIL = auto()
    DEALLOCATION_FAIL = auto()


class IpAddressStatus(AutoNameStrEnum):
    FREE = auto()
    RESERVED = auto()
    ALLOCATED = auto()
    RELEASING = auto()
    UNAVAILABLE = auto()


class ServerStatus(AutoNameStrEnum):
    # Server level statuses
    INITIALIZING = auto()
    INIT_FAIL = auto()
    READY = auto()
    DECOMMISSIONING = auto()
    DECOMMISSIONED = auto()
    DECOMMISSION_FAIL = auto()


class ComputeUnitInDB(BaseModel):
    compute_id: str
    hostname: str
    ordinal: int
    cpu_range: str
    cpu_count: int
    cpu_set: str
    status: str
    started_at: dt.datetime | None = None
    tags: dict[str, Any] | None = None


class InitComputeUnit(BaseModel):
    ordinal: int
    cpu_range: str
    cpu_set: str
    cpu_count: int

    def as_playbook_vars(self) -> dict:
        return {
            "ordinal": self.ordinal,
            "cpu_range": self.cpu_range,
            "cpu_set": self.cpu_set,
            "cpu_count": self.cpu_count,
        }

    def as_compute_unit(self, hostname: str) -> ComputeUnitInDB:
        return ComputeUnitInDB(
            compute_id="",  # generated by the database
            hostname=hostname,
            ordinal=self.ordinal,
            cpu_range=self.cpu_range,
            cpu_count=self.cpu_count,
            cpu_set=self.cpu_set,
            status=ComputeUnitStatus.FREE,
        )


class ComputeUnitOverview(ComputeUnitInDB):
    server_private_ip: str
    server_public_ip: str | None = None
    server_admin_user: str
    region: str
    zone: str


class ComputeUnitRequest(BaseModel):
    allocation_id: str | None = None
    login_user: str | None = None
    compute_id: str | None = None
    cpu_count: int | None = None
    region: str | None = None
    zone: str | None = None
    ip_address: str | None = None
    tags: dict[str, Any] | None = None
    ssh_public_key: str


class AllocationCreateCommand(BaseModel):
    allocation_id: str
    compute_id: str
    ssh_public_key: str


class AllocationCreateResponse(BaseModel):
    allocation_id: str
    job_id: int


class AllocationDeallocateCommand(BaseModel):
    allocation_id: str
    compute_id: str


class AllocationScaleRequest(BaseModel):
    compute_id: str | None = None
    cpu_count: int | None = None
    region: str | None = None
    zone: str | None = None


class AllocationScaleCommand(AllocationScaleRequest):
    allocation_id: str


class AllocationInDB(BaseModel):
    allocation_id: str
    login_user: str
    ip_address: str
    compute_id: str | None = None
    current_host: str | None = None
    status: str
    tags: dict[str, Any] | None = None
    created_at: dt.datetime | None = None
    updated_at: dt.datetime | None = None


class IpPoolAddressInDB(BaseModel):
    ip_address: str
    status: str
    allocation_id: str | None = None
    current_host: str | None = None
    created_at: dt.datetime | None = None
    updated_at: dt.datetime | None = None


class IpPoolInsertRequest(BaseModel):
    ip_addresses: list[str] = Field(min_length=1)


class IpPoolAllocateRequest(BaseModel):
    ip_address: str


class ValidatedLicense(BaseModel):
    license_id: str
    customer: str
    issued_at: dt.datetime
    expires_at: dt.datetime
    features: list[str] = Field(default_factory=list)
    limits: dict[str, Any] = Field(default_factory=dict)
    key_id: str


class LicenseStatusResponse(BaseModel):
    edition: str
    valid: bool
    reason: str | None = None
    license: ValidatedLicense | None = None


class BaseServer(BaseModel):
    hostname: str
    private_ip: str
    public_ip: str | None = None
    server_admin_user: str
    region: str
    zone: str | None = None
    cpu_count: int | None = None
    mem_gb: int | None = None
    disk_count: int | None = None
    disk_size_gb: int | None = None
    tags: dict[str, Any] | None = None


class ServerInDB(BaseServer):
    status: str


class ServerComputeUnitInitSpec(BaseModel):
    ordinal: int = Field(gt=0)
    cpu_range: str


class ServerInitRequest(BaseServer):
    compute_units: list[ServerComputeUnitInitSpec]

    @model_validator(mode="after")
    def validate_compute_units(self):
        if not self.compute_units:
            raise ValueError("compute_units must contain at least one compute unit.")

        ordinals = [cu.ordinal for cu in self.compute_units]
        if len(set(ordinals)) != len(ordinals):
            raise ValueError("compute_units ordinals must be unique.")

        seen_cpus: set[int] = set()
        for cu in self.compute_units:
            cpu_ids = _cpu_ids_for_range(cu.cpu_range)
            if seen_cpus.intersection(cpu_ids):
                raise ValueError("compute_units cpu_range values must not overlap.")
            seen_cpus.update(cpu_ids)

        return self


class ServerDecommRequest(BaseModel):
    hostname: str
