---
#
# Playbook invoked by Kloigos after each `allocate` call.
#
# The following extra-vars are passed:
#   compute_id
#   ssh_public_key
#
- name: GATHER COMPUTE UNIT TO ALLOCATE
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    kloigos_server: "http://127.0.0.1:8000"
  tasks:
    - name: gather new server details
      ansible.builtin.uri:
        url: "{{ kloigos_server }}/compute_units?compute_id={{ compute_id }}"
        method: GET
        status_code: 200
      register: instances

    - name: print list of instances
      debug:
        var: instances.json

    - name: Build ansible inventory dynamically
      add_host:
        name: "{{ item.compute_id }}"
        ansible_user: ubuntu
        public_hostname: "{{ item.hostname }}"
        ansible_host: "{{ item.ip }}"
        public_ip: "{{ item.ip }}"
        cu_user: "c{{ item.cpu_range.replace(':', '-') }}"
        ports_range: "{{ item.ports_range }}"
        cpu_count: "{{ item.cpu_count }}"
        groups: new_alloc

      loop: "{{ instances.json }}"

- name: ALLOCATE COMPUTE UNIT
  hosts: new_alloc
  gather_facts: no
  become: yes
  tasks:
    - name: setup SSH key so user can login
      copy:
        content: |
          {{ ssh_public_key }}
        dest: /home/{{ cu_user }}/.ssh/authorized_keys

    - name: create welcome file
      copy:
        content: |
          WELCOME TO COMPUTE UNIT `{{ name }}`!

          This compute unit features:
            - CPU count: {{ cpu_count }}
            - Memory:
            - Max running processes: 
            - Ports assigned: {{ ports_range }}
            - Network bandwidth:
            - Disk volume at /mnt/{{ cu_user }}
            - IOPS/MBPS:

          
          You're not root, but you can still use systemd
          to run your services.
          Make sure you save your .service files at directory

          ~/.config/systemd/user/

          and you manage the service using the `--user` flag, Example:  

          systemctl --user daemon-reload
          systemctl --user enable myservice
          systemctl --user start myservice

        dest: /home/{{ cu_user }}/WELCOME.txt