---
- name: GATHER COMPUTE UNITS TO CLEANUP
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    kloigos_server: "http://127.0.0.1:8000"
  tasks:
    - name: gather instances with status set to terminating
      ansible.builtin.uri:
        url: "{{ kloigos_server }}/servers?status=terminating"
        method: GET
        status_code: 200
      register: instances

    - name: print list of instances
      debug:
        var: instances.json

    - name: Build ansible inventory dynamically
      add_host:
        name: "{{ item.compute_id }}"
        ansible_user: ubuntu
        public_hostname: "{{ item.hostname }}"
        ansible_host: "{{ item.ip }}"
        public_ip: "{{ item.ip }}"
        cpu_list: "{{ item.cpu_list }}"
        cpu_range: "c{{ item.cpu_range.replace(':', '-') }}"
        ports_range: "{{ item.ports_range }}"
        groups: cleanup
        cloud: "{{ item.region | default('k1') }}"
        region: "{{ item.region | default('r1') }}"
        zone: "{{ item.zone | default('a') }}"

      loop: "{{ instances.json }}"

- name: CLEANUP COMPUTE UNIT
  hosts: cleanup
  gather_facts: no
  become: yes
  tasks:
    - name: remove all files from the compute_unit
      shell: |
        rm -rf {{ cpu_range }}/*
        rm -rf /opt/{{ cpu_range }}/*
        rm -rf /var/lib/cockroach/{{ cpu_range }}/*
        rm -rf /mnt/cockroach/{{ cpu_range }}/*
        rm -rf /etc/systemd/system/cockroachdb-{{ cpu_range }}.service
      