---
#
# Playbook invoked by Kloigos after each `allocate` call.
#
# The following extra-vars are passed:
#   compute_id
#   hostname
#.  ip
#.  cpu_range
#.  cpu_count
#.  port_range
#   ssh_public_key
#
#
- name: GATHER COMPUTE UNIT TO ALLOCATE
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
    - name: Build ansible inventory dynamically
      add_host:
        name: "{{ compute_id }}"
        ansible_user: ubuntu
        public_hostname: "{{ hostname }}"
        ansible_host: "{{ ip }}"
        public_ip: "{{ ip }}"
        cu_user: "c{{ cpu_range.replace(':', '-') }}"
        port_range: "{{ port_range }}"
        cpu_count: "{{ cpu_count }}"
        groups: new_alloc


- name: ALLOCATE COMPUTE UNIT
  hosts: new_alloc
  gather_facts: no
  become: yes
  tasks:
    - name: setup SSH key so user can login
      copy:
        content: |
          {{ ssh_public_key }}
        dest: /home/{{ cu_user }}/.ssh/authorized_keys

    - name: create welcome file
      copy:
        content: |
          WELCOME TO COMPUTE UNIT `{{ compute_id }}`!

          This compute unit features:
            - CPU count: {{ cpu_count }}
            - Memory:
            - Max running processes: 
            - Ports assigned: {{ port_range }}
            - Network bandwidth:
            - Disk volume at /mnt/{{ cu_user }}
            - IOPS/MBPS:

          
          You're not root, but you can still use systemd
          to run your services.
          Make sure you save your .service files at directory

          ~/.config/systemd/user/

          and you manage the service using the `--user` flag, Example:  

          systemctl --user daemon-reload
          systemctl --user enable myservice
          systemctl --user start myservice

        dest: /home/{{ cu_user }}/WELCOME.txt
