---
#
# Playbook invoked by Kloigos after each `deallocate` call.
#
#   compute_id
#   hostname
#   ip
#   cu_user
#
- name: GATHER COMPUTE UNITS TO DEALLOCATE
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
    - name: Build ansible inventory dynamically
      add_host:
        name: "{{ compute_id }}"
        ansible_user: ubuntu
        public_hostname: "{{ hostname }}"
        ansible_host: "{{ ip }}"
        public_ip: "{{ ip }}"
        cu_user: "{{ cu_user }}"

        groups: dealloc

- name: CLEANUP COMPUTE UNIT
  hosts: dealloc
  gather_facts: no
  become: yes
  tasks:
    - name: finding id for user
      shell: |
        id -u {{ cu_user }}
      register: user_id

    - name: remove ssh key to block any new connection
      shell: |
        rm -f /home/{{ cu_user }}/.ssh/authorized_keys

    - name: stop the user systemd instance to stop any running process
      shell: |
        systemctl stop user@{{ user_id.stdout }}.service

    - name: severe any open connection
      shell: |
        loginctl kill-user {{ cu_user }} || true

    - name: remove all files from the compute_unit
      shell: |
        rm -rf /home/{{ cu_user }}/*
        rm -rf /opt/{{ cu_user }}/*
        rm -rf /mnt/{{ cu_user }}/*

    - name: recreate .ssh with safe perms (empty, no keys)
      shell: |
        mkdir -p /home/{{ cu_user }}/.ssh
        chown {{ cu_user }}:{{ cu_user }} /home/{{ cu_user }}/.ssh
        chmod 700 /home/{{ cu_user }}/.ssh

        touch /home/{{ cu_user }}/.ssh/authorized_keys
        chown {{ cu_user }}:{{ cu_user }} /home/{{ cu_user }}/.ssh/authorized_keys
        chmod 600 /home/{{ cu_user }}/.ssh/authorized_keys
