---
#
# Playbook invoked by Kloigos after each `deallocate` call.
#
- name: GATHER COMPUTE UNITS TO DEALLOCATE
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    kloigos_server: "http://127.0.0.1:8000"
  tasks:
    - name: gather compute units with status set to terminating
      ansible.builtin.uri:
        url: "{{ kloigos_server }}/compute_units?status=terminating"
        method: GET
        status_code: 200
      register: instances

    - name: print list of instances
      debug:
        var: instances.json

    - name: Build ansible inventory dynamically
      add_host:
        name: "{{ item.compute_id }}"
        ansible_user: ubuntu
        public_hostname: "{{ item.hostname }}"
        ansible_host: "{{ item.ip }}"
        public_ip: "{{ item.ip }}"
        cu_user: "c{{ item.cpu_range.replace(':', '-') }}"
        groups: dealloc

      loop: "{{ instances.json }}"

- name: CLEANUP COMPUTE UNIT
  hosts: dealloc
  gather_facts: no
  become: yes
  tasks:
    - name: remove all files from the compute_unit
      shell: |
        rm -rf {{ cpu_range }}/*
        rm -rf /opt/{{ cpu_range }}/*
        rm -rf /var/lib/{{ cpu_range }}/*
        rm -rf /mnt/{{ cpu_range }}/*
        rm -rf /etc/systemd/system/{{ cpu_range }}-*.service
      