import ipaddress

from kloigos.models import (
    AllocationInDB,
    AllocationNetworkPolicy,
    AllocationStatus,
    ComputeUnitNotFoundError,
    EffectiveNetworkRule,
    HostNetworkPolicy,
    SecurityGroupDirection,
    SecurityGroupIpVersion,
    SecurityGroupProtocol,
    SecurityGroupRuleInDB,
)

from ..repos import Repo


class NetworkPolicyService:
    """Build and render effective nftables policy for allocation security groups."""

    def __init__(self, repo: Repo):
        self.repo = repo

    def build_allocation_policy(self, allocation_id: str) -> AllocationNetworkPolicy:
        """Build the effective network policy for one allocation."""
        allocation = self._get_allocation(allocation_id)
        return self._build_allocation_policy(allocation)

    def build_host_policy(self, hostname: str) -> HostNetworkPolicy:
        """Build the complete effective network policy for one host."""
        allocations = [
            allocation
            for allocation in self.repo.get_allocations(current_host=hostname)
            if allocation.status != AllocationStatus.DEALLOCATED
            and allocation.ip_address
            and allocation.current_host
        ]
        policies = [
            self._build_allocation_policy(allocation) for allocation in allocations
        ]
        policies.sort(key=lambda policy: policy.allocation_id)
        return HostNetworkPolicy(hostname=hostname, allocations=policies)

    def render_host_policy(self, hostname: str) -> str:
        """Render one host's effective network policy as nftables configuration."""
        return render_nftables_policy(self.build_host_policy(hostname))

    def _build_allocation_policy(
        self,
        allocation: AllocationInDB,
    ) -> AllocationNetworkPolicy:
        if not allocation.current_host:
            raise ComputeUnitNotFoundError(
                f"Allocation '{allocation.allocation_id}' has no current host."
            )

        ip_version = _ip_version_for_address(allocation.ip_address)
        raw_rules = []
        for attachment in self.repo.get_security_group_attachments(
            allocation_id=allocation.allocation_id
        ):
            raw_rules.extend(
                self.repo.get_security_group_rules(
                    security_group_id=attachment.security_group_id
                )
            )

        effective_rules = _effective_rules_for_ip_version(raw_rules, ip_version)
        ingress_rules = [
            rule
            for rule in effective_rules
            if rule.direction == SecurityGroupDirection.INGRESS
        ]
        egress_rules = [
            rule
            for rule in effective_rules
            if rule.direction == SecurityGroupDirection.EGRESS
        ]
        return AllocationNetworkPolicy(
            allocation_id=allocation.allocation_id,
            login_user=allocation.login_user,
            hostname=allocation.current_host,
            ip_address=allocation.ip_address,
            ip_version=ip_version,
            ingress_rules=ingress_rules,
            egress_rules=egress_rules,
        )

    def _get_allocation(self, allocation_id: str) -> AllocationInDB:
        matches = self.repo.get_allocations(allocation_id=allocation_id)
        if not matches:
            raise ComputeUnitNotFoundError(
                f"Allocation '{allocation_id}' was not found."
            )
        return matches[0]


def render_nftables_policy(policy: HostNetworkPolicy) -> str:
    """Render a complete Kloigos-managed nftables table for a host policy."""
    lines = [
        "# Generated by Kloigos. Do not edit by hand.",
        "table inet kloigos {",
        "  chain kloigos_input {",
        "    type filter hook input priority filter; policy accept;",
    ]

    for allocation in policy.allocations:
        lines.extend(_render_allocation_ingress(allocation))

    lines.extend(
        [
            "  }",
            "",
            "  chain kloigos_output {",
            "    type filter hook output priority filter; policy accept;",
        ]
    )

    for allocation in policy.allocations:
        lines.extend(_render_allocation_egress(allocation))

    lines.extend(["  }", "}"])
    return "\n".join(lines) + "\n"


def _effective_rules_for_ip_version(
    rules: list[SecurityGroupRuleInDB],
    ip_version: SecurityGroupIpVersion,
) -> list[EffectiveNetworkRule]:
    by_key: dict[tuple, EffectiveNetworkRule] = {}
    for rule in rules:
        if rule.ip_version != ip_version:
            continue
        effective = EffectiveNetworkRule(
            direction=rule.direction,
            protocol=rule.protocol,
            port_from=rule.port_from,
            port_to=rule.port_to,
            cidr=rule.cidr,
            ip_version=rule.ip_version,
            source_rule_ids=[rule.rule_id],
            source_security_group_ids=[rule.security_group_id],
            description=rule.description,
        )
        key = effective.key()
        if key not in by_key:
            by_key[key] = effective
            continue
        existing = by_key[key]
        if rule.rule_id not in existing.source_rule_ids:
            existing.source_rule_ids.append(rule.rule_id)
        if rule.security_group_id not in existing.source_security_group_ids:
            existing.source_security_group_ids.append(rule.security_group_id)

    for rule in by_key.values():
        rule.source_rule_ids.sort()
        rule.source_security_group_ids.sort()

    return sorted(
        by_key.values(),
        key=lambda rule: (
            rule.direction,
            rule.ip_version,
            rule.protocol,
            rule.cidr,
            rule.port_from or 0,
            rule.port_to or 0,
        ),
    )


def _render_allocation_ingress(allocation: AllocationNetworkPolicy) -> list[str]:
    lines = [f"    # ingress for allocation {allocation.allocation_id}"]
    for rule in allocation.ingress_rules:
        lines.append(_render_rule(rule, allocation.ip_address, inbound=True))
    family = _nft_family(allocation.ip_version)
    lines.append(
        f"    {family} daddr {allocation.ip_address} drop "
        f'comment "{_comment("default deny ingress", allocation.allocation_id)}"'
    )
    return lines


def _render_allocation_egress(allocation: AllocationNetworkPolicy) -> list[str]:
    if not allocation.egress_rules:
        return [
            f"    # egress for allocation {allocation.allocation_id}: default allow"
        ]

    lines = [f"    # egress for allocation {allocation.allocation_id}"]
    for rule in allocation.egress_rules:
        lines.append(_render_rule(rule, allocation.ip_address, inbound=False))
    family = _nft_family(allocation.ip_version)
    lines.append(
        f"    {family} saddr {allocation.ip_address} drop "
        f'comment "{_comment("default deny egress", allocation.allocation_id)}"'
    )
    return lines


def _render_rule(
    rule: EffectiveNetworkRule,
    allocation_ip: str,
    *,
    inbound: bool,
) -> str:
    family = _nft_family(rule.ip_version)
    allocation_match = "daddr" if inbound else "saddr"
    remote_match = "saddr" if inbound else "daddr"
    parts = [
        f"    {family} {allocation_match} {allocation_ip}",
        f"{family} {remote_match} {rule.cidr}",
    ]
    parts.extend(_protocol_match(rule))
    parts.append("accept")
    parts.append(f'comment "{_rule_comment(rule)}"')
    return " ".join(parts)


def _protocol_match(rule: EffectiveNetworkRule) -> list[str]:
    if rule.protocol == SecurityGroupProtocol.ALL:
        return []
    if rule.protocol == SecurityGroupProtocol.ICMP:
        return ["meta", "l4proto", "icmp"]
    if rule.protocol == SecurityGroupProtocol.ICMPV6:
        return ["meta", "l4proto", "ipv6-icmp"]

    match = [rule.protocol.value]
    if rule.port_from is None:
        return ["meta", "l4proto", rule.protocol.value]
    port_expr = str(rule.port_from)
    if rule.port_to is not None and rule.port_to != rule.port_from:
        port_expr = f"{rule.port_from}-{rule.port_to}"
    match.extend(["dport", port_expr])
    return match


def _ip_version_for_address(ip_address: str) -> SecurityGroupIpVersion:
    ip = ipaddress.ip_address(ip_address)
    if ip.version == 4:
        return SecurityGroupIpVersion.IPV4
    return SecurityGroupIpVersion.IPV6


def _nft_family(ip_version: SecurityGroupIpVersion) -> str:
    if ip_version == SecurityGroupIpVersion.IPV6:
        return "ip6"
    return "ip"


def _rule_comment(rule: EffectiveNetworkRule) -> str:
    label = rule.description or ",".join(rule.source_security_group_ids)
    return _comment(label, ",".join(rule.source_rule_ids))


def _comment(*parts: str) -> str:
    text = " ".join(part for part in parts if part)
    return text.replace("\\", "\\\\").replace('"', '\\"')[:120]
