#
# Example Playbook showing how to use Kloigos
# to use provisioned compute units to
# deploy a CockroachDB cluster.
#
---
- name: PROVISION COMPUTE UNITS
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    deployment_id: fab8
    kloigos_server: "http://127.0.0.1:8000/api"
  tasks:
    - name: get the previously allocated instances
      ansible.builtin.uri:
        url: "{{ kloigos_server }}/compute_units?deployment_id={{ deployment_id }}"
        method: GET
        headers:
          Content-Type: application/json
        status_code: 200
      register: instances

    - name: print list of instances
      debug:
        msg: "{{ instances.json }}"

    - name: Build ansible inventory dynamically
      add_host:
        name: "{{ item.compute_id }}"
        ansible_user: "{{ item.cu_user }}"
        public_hostname: "{{ item.hostname }}"
        ansible_host: "{{ item.ip }}"
        public_ip: "{{ item.ip }}"
        cpu_list: "{{ item.cpu_list }}"
        cpu_range: "{{ item.cpu_range.replace(':', '-') }}"
        cu_user: "c{{ item.cpu_range.replace(':', '-') }}"
        port_range: "{{ item.port_range }}"
        groups: "{{ item.tags.groups | default(['cockroachdb']) + [item.tags.deployment_id] }}"
        cloud: "{{ item.cloud | default('k5s') }}"
        region: "{{ item.region | default('r1') }}"
        zone: "{{ item.zone | default('a') }}"

      loop: "{{ instances.json }}"

    - name: save simplified list of hosts
      copy:
        content: |
          {% for item in groups %}
          {% if item not in ['all', 'ungrouped'] %}
          [{{item}}]
          {% for entry in groups[item] %}
          {{ entry }}  {{hostvars[entry].ansible_host }} {{hostvars[entry].cpu_range }} {{hostvars[entry].port_range }} {{hostvars[entry].cloud }}-{{hostvars[entry].region }}-{{hostvars[entry].zone }} 
          {% endfor %}

          {% endif %}
          {% endfor %}
        dest: "{{ deployment_id }}.simple.ini"

- name: DEPLOY COCKROACHDB
  hosts: cockroachdb
  gather_facts: yes
  become: no
  vars:
    cockroachdb_version: v25.4.0
    cockroachdb_secure: no
    cockroachdb_certificates_dir: certs
    cockroachdb_certificates_clients:
      - root
    cockroachdb_sql_port: 57
    cockroachdb_http_addr_ip: "0.0.0.0"
    cockroachdb_http_port: 80
    # cockroachdb_store:
    #   - /mnt/cockroach
    cockroachdb_secure_flag: --certs-dir=/var/lib/cockroach/certs
    cockroachdb_insecure_flag: --insecure
    cockroachdb_repo_url: https://binaries.cockroachdb.com
    cockroachdb_locality: "cloud={{ cloud | default('') }},region={{ region | default('') }},zone={{ zone | default('') }}"
    cockroachdb_advertise_addr: "{{ public_ip | default('') }}"
    cockroachdb_listen_addr: "0.0.0.0"
    cockroachdb_attrs: std
    cockroachdb_cache: ".35"
    cockroachdb_max_sql_memory: ".35"
    cockroachdb_env_vars: []
    cockroachdb_rpc_port: 77
    cockroachdb_max_offset: 250ms

  tasks:
    - name: Create the binary-type map
      set_fact:
        # map the machine CPU type to the matching filename component
        bin_arch:
          aarch64: arm64
          x86_64: amd64

    - name: Check that the CockroachDB tarball exists locally
      stat:
        path: "cockroach-{{ cockroachdb_version }}.linux-{{ bin_arch[ansible_architecture] }}.tgz"
      register: _stat_result

    - name: Download CockroachDB binary
      shell: |
        wget -q {{ cockroachdb_repo_url }}/cockroach-{{ cockroachdb_version }}.linux-{{ bin_arch[ansible_architecture] }}.tgz
      when: not _stat_result.stat.exists

    - name: Install CockroachDB binary
      shell: |
        tar xvf cockroach-{{ cockroachdb_version }}.linux-{{ bin_arch[ansible_architecture] }}.tgz
        mv -f cockroach-{{ cockroachdb_version }}.linux-{{ bin_arch[ansible_architecture] }}/cockroach /opt/{{ cu_user }}
        chmod 755 /opt/{{ cu_user }}/cockroach
        rm -rf cockroach-{{ cockroachdb_version }}.linux-{{ bin_arch[ansible_architecture] }}

    - name: Create CockroachDB store directory
      shell: |
        mkdir -p /mnt/{{ cu_user }}/cockroach
        chmod 755 /mnt/{{ cu_user }}/cockroach

    - name: Group hosts dynamically based on region
      group_by:
        key: "crdbregion_{{ region }}"

    - name: Create CockroachDB store directory
      shell: |
        mkdir -p /home/{{ cu_user }}/.config/systemd/user/
        chmod 755 /home/{{ cu_user }}/.config/systemd/user/

    - name: Copy systemd template cockroachdb.service
      copy:
        content: |
          [Unit]
          Description=Cockroach Database cluster node
          [Service]
          Type=notify
          WorkingDirectory=/opt/{{ cu_user }}
          {% for v in cockroachdb_env_vars %}
          Environment="{{ v }}"
          {% endfor %}
          ExecStart=/opt/{{ cu_user }}/cockroach start \
              {{ (cockroachdb_secure) | ternary(cockroachdb_secure_flag, cockroachdb_insecure_flag) }} \
              --store=/mnt/{{ cu_user }}/cockroach/ \
              --listen-addr={{ cockroachdb_listen_addr }}:{{ port_range.split('-')[0] | int + cockroachdb_rpc_port }} \
              --advertise-addr={{ cockroachdb_advertise_addr }}:{{ port_range.split('-')[0] | int + cockroachdb_rpc_port }} \
              --sql-addr=:{{ port_range.split('-')[0] | int + cockroachdb_sql_port }} \
              --cache={{ cockroachdb_cache }} \
              --max-sql-memory={{ cockroachdb_max_sql_memory }} \
              --http-addr={{ cockroachdb_http_addr_ip }}:{{ port_range.split('-')[0] | int + cockroachdb_http_port }} \
              {% for g in groups -%}
              {% if g.startswith("crdbregion_") -%}
              {% for joinhost in (groups[g] | sort)[:3] -%}
              --join={{ hostvars[joinhost].public_ip }}:{{ hostvars[joinhost].port_range.split('-')[0] | int + cockroachdb_rpc_port }} \
              {% endfor -%}
              {% endif -%}
              {% endfor -%}
              --locality={{ cockroachdb_locality }} \
              --max-offset={{ cockroachdb_max_offset }}
          TimeoutStopSec=300
          LimitNOFILE=65000
          Restart=on-failure
          SuccessExitStatus=SIGKILL
          RestartSec=10
          StandardOutput=syslog
          StandardError=syslog
          SyslogIdentifier={{ cu_user }}-cockroach
          [Install]
          WantedBy=default.target
        dest: /home/{{ cu_user }}/.config/systemd/user/{{ cu_user }}-cockroachdb.service
        mode: 0644
        force: yes

    - name: Ensure cockroachdb service is restarted
      shell: |
        systemctl --user daemon-reload
        systemctl --user enable {{ cu_user }}-cockroachdb
        systemctl --user restart {{ cu_user }}-cockroachdb

    - name: Find the first region host
      set_fact:
        init_host: >-
          {{
            groups
            | dict2items
            | selectattr('key', 'match', '^crdbregion_')
            | map(attribute='value')
            | flatten
            | sort
            | first
          }}
      run_once: yes

    - name: Init Cluster
      run_once: yes
      shell: |
        /opt/{{ cu_user }}/cockroach init \
          {{ (cockroachdb_secure) | ternary(cockroachdb_secure_flag, cockroachdb_insecure_flag) }} \
          --host={{ hostvars[init_host].public_ip }}:{{ hostvars[init_host].port_range.split('-')[0] | int + cockroachdb_rpc_port }}
      register: result
      failed_when: result.rc != 0 and 'cluster has already been initialized' not in result.stderr and 'unable to bootstrap due to internal error' not in result.stderr

- name: GET DATA FROM COCKROACHDB CLUSTER
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
    - name: Collect cloud, region and public_ip for cockroachdb servers
      set_fact:
        cockroachdb: >-
          {{
            groups['cockroachdb']
            | map('extract', hostvars) 
            | map('dict2items')                  
            | map('selectattr', 'key', 'in', ['ansible_host', 'cloud', 'region', 'public_ip'])
            | map('items2dict')    | list              
          }}

    # - name: Collect cloud, region and public_ip for haproxy servers
    #   set_fact:
    #     haproxy: >-
    #       {{
    #         groups['haproxy']
    #         | map('extract', hostvars) 
    #         | map('dict2items')                  
    #         | map('selectattr', 'key', 'in', ['ansible_host', 'cloud', 'region', 'public_ip'])
    #         | map('items2dict')    | list              
    #       }}

    - name: Data
      debug:
        msg:
          cockroachdb: "{{ cockroachdb }}"
          # haproxy: "{{ haproxy }}"