#!/usr/bin/env python3
from __future__ import annotations

import ast
import sys
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "CODEMAP.md"
SKIP_DIRS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "build",
    "dist",
}


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def load_pyproject() -> dict[str, Any]:
    path = ROOT / "pyproject.toml"
    if not path.exists():
        return {}
    return tomllib.loads(path.read_text())


def project_name(pyproject: dict[str, Any]) -> str:
    poetry = pyproject.get("tool", {}).get("poetry", {})
    project = pyproject.get("project", {})
    return poetry.get("name") or project.get("name") or ROOT.name


def script_rows(pyproject: dict[str, Any]) -> list[str]:
    poetry_scripts = pyproject.get("tool", {}).get("poetry", {}).get("scripts", {})
    project_scripts = pyproject.get("project", {}).get("scripts", {})
    scripts = {**project_scripts, **poetry_scripts}
    return [f"- `{name}` -> `{target}`" for name, target in sorted(scripts.items())]


def package_roots(pyproject: dict[str, Any]) -> list[Path]:
    poetry = pyproject.get("tool", {}).get("poetry", {})
    roots: set[Path] = set()

    for package in poetry.get("packages", []):
        include = package.get("include")
        if include:
            path = ROOT / include
            if path.exists():
                roots.add(path)

    name_root = ROOT / project_name(pyproject).replace("-", "_")
    if name_root.exists():
        roots.add(name_root)

    for path in ROOT.iterdir():
        if path.name in SKIP_DIRS or path.name.startswith("."):
            continue
        if path.is_dir() and (path / "__init__.py").exists():
            roots.add(path)

    return sorted(roots)


def iter_python_files(roots: list[Path]) -> list[Path]:
    files: list[Path] = []
    for root in roots:
        for path in root.rglob("*.py"):
            if any(part in SKIP_DIRS for part in path.parts):
                continue
            files.append(path)
    return sorted(files)


def public_defs(tree: ast.Module) -> tuple[list[str], list[str]]:
    classes: list[str] = []
    functions: list[str] = []

    for node in tree.body:
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            classes.append(node.name)
        elif isinstance(
            node, (ast.FunctionDef, ast.AsyncFunctionDef)
        ) and not node.name.startswith("_"):
            functions.append(node.name)

    return classes, functions


def import_names(tree: ast.Module) -> list[str]:
    imports: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                imports.add(alias.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom) and node.module:
            if node.level:
                imports.add("." * node.level + node.module)
            else:
                imports.add(node.module.split(".")[0])
    return sorted(imports)


def module_rows(files: list[Path]) -> list[str]:
    rows = []
    for path in files:
        tree = ast.parse(path.read_text(), filename=str(path))
        doc = ast.get_docstring(tree)
        classes, functions = public_defs(tree)
        imports = import_names(tree)

        details = []
        if doc:
            details.append(doc.splitlines()[0])
        if classes:
            details.append("classes: " + ", ".join(classes))
        if functions:
            details.append("functions: " + ", ".join(functions))
        if imports:
            details.append("imports: " + ", ".join(imports))

        rows.append(
            f"| `{rel(path)}` | {'; '.join(details) if details else 'no public surface'} |"
        )
    return rows


def render() -> str:
    pyproject = load_pyproject()
    roots = package_roots(pyproject)
    files = iter_python_files(roots)
    scripts = script_rows(pyproject)

    lines = [
        "# Code Map",
        "",
        "<!-- Generated by tools/generate_codemap.py. Do not edit by hand. -->",
        "",
        "This file is a deterministic map of the Python package surface in this repository.",
        "Regenerate it after structural code changes with:",
        "",
        "```bash",
        "python3 tools/generate_codemap.py",
        "```",
        "",
        "## Project",
        "",
        f"- Name: `{project_name(pyproject)}`",
        f"- Package roots: {', '.join(f'`{rel(root)}`' for root in roots) or 'none found'}",
        "",
        "## Entry Points",
        "",
    ]

    lines.extend(scripts or ["- none found"])
    lines.extend(
        [
            "",
            "## Modules",
            "",
            "| File | Public Surface |",
            "| --- | --- |",
            *module_rows(files),
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    content = render()
    if sys.argv[1:] == ["--check"]:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != content:
            print("CODEMAP.md is out of date. Run: python3 tools/generate_codemap.py")
            raise SystemExit(1)
        return

    if sys.argv[1:]:
        print("Usage: python3 tools/generate_codemap.py [--check]")
        raise SystemExit(2)

    OUTPUT.write_text(content)


if __name__ == "__main__":
    main()
